services:
  db:
    build:
      context: ./db/docker
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    restart: always
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    env_file:
      - .env.local
    volumes:
      - ./db/changelog.xml:/liquibase/changelog.xml
      - ./db/scripts:/liquibase/scripts
      - ./db/drivers:/liquibase/lib
    command: >
      --classpath=/liquibase/lib/postgresql.jar
      --url=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      --changeLogFile=changelog.xml
      --username=postgres
      --password=${POSTGRES_PASSWORD}
      update
    depends_on:
      - db

volumes:
  pgdata:
