#version: '3'
services:
  db:
    image: postgres:17
    #env_file:
    #  - ./.env.local
    environment:
      POSTGRES_DB: volunteer_next_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar
      #POSTGRES_PORT: "5432"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    env_file:
      - .env.local
    volumes:
      - ./db/changelog.xml:/liquibase/changelog.xml
      - ./db/scripts:/liquibase/scripts
    command: >
      --url=jdbc:postgresql://db:5432/volunteer_next_db
      --changeLogFile=changelog.xml
      --username=postgres
      --password=foobar
      update
    depends_on:
      - db

volumes:
  pgdata:
